### ISSUE TITLE
Pusher not working when called from scheduled event

### ISSUE THREAD

**Issue by wilcomx** [mendixlabs/pusher-notify-listen#3]
Hi there,

Bumped into an issue with pusher where it was throwing null pointer exceptions when fired from a scheduled event.

I created a workaround by replacing line 96 of Notify.java with:
``
String sender = "Application";
if (this.context().getCurrentUserObject() != null) {
    sender = this.context().getCurrentUserObject().getValue(getContext(), "Name");
}
``

Hope this will benefit you.

Cheers,

Wilco
(Mendix)

**Comment by Andries-Smit** [comment]
Hi Wilco

Thanks you, we will take this change into account.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Thanks, the solution is now available in v1.0.5
